# Before launching the application be sure that the followings are set up in your enviroment variables or here as strings

development:

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> # Get it from the ScrumMaster or ProductOwner
  
  database_username: <%= ENV["DATABASE_PASSWORD"] %> # Your database username

  database_password: <%= ENV["DATABASE_PASSWORD"] %> # Your database password

  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %> # Get it from the ScrumMaster or ProductOwner

  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %> # Get it from the ScrumMaster or ProductOwner

  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %> # Get it from the ScrumMaster or ProductOwner

  google_client_secreet: <%= ENV["GOOGLE_CLIENT_SECREET"] %> # Get it from the ScrumMaster or ProductOwner

  redirect_uri: http://localhost:3000/users/auth/google_oauth2/callback



staging:

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  database_password: <%= ENV["RDS_PASSWORD"] %>

  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>

  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>

  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>

  google_client_secreet: <%= ENV["GOOGLE_CLIENT_SECREET"] %>

  redirect_uri: http://selection-staging.greenfox.academy/users/auth/google_oauth2/callback



production:

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  database_password: <%= ENV["RDS_PASSWORD"] %>

  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>

  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>

  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>

  google_client_secreet: <%= ENV["GOOGLE_CLIENT_SECREET"] %>

  redirect_uri: http://selection.greenfox.academy/users/auth/google_oauth2/callback



test:

  secret_key_base: 5e6fcee4e2e10d63646468b0534c5eb693a3192fdd9a2f84e1605ed7023041ce0696bb31a037a130b4086f32d89e7c5b2a3d133c5ddbe1e3c3ba03b4c6c56526

  database_password: '123'

  github_client_id: ed08b66e3e180170d80b

  github_client_secret: 7ddb55b7b91d85bc4c8dbca5a09d1131dd4c5d89

  google_client_id: 397190566717-ff44llguvs4bc1kvvcgn6jq2d5arufc0.apps.googleusercontent.com

  google_client_secreet: dkdaTVnkxDKCcYce2z-a5D_J